version: '3'
services: 
  keycloak:
    image: 'quay.io/keycloak/keycloak:12.0.2'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=andi
      # - PROXY_ADDRESS_FORWARDING=true
      # - KEYCLOAK_LOGLEVEL=DEBUG
      # - ROOT_LOGLEVEL=DEBUG
      # - DEBUG=true
    ports: 
      - '8080:8080'
      # - '127.0.0.1:8080:8080'
      # - '172.17.208.1:8080:8080'
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes: 
      - /app/node_modules
      - ./:/app
    environment: 
      - PORT=3000
      # - AUTH_SERVER_URL=http://192.168.1.14:8080/auth/
      #using the localhost for keycloak does NOT work - Access denied
      #using the external IP for keycloak is working fine
      # - AUTH_SERVER_URL=http://172.17.208.1:8080/auth/
      - REACT_APP_AUTH_SERVER_URL=http://localhost:8080/auth/      
      - REACT_APP_AUTH_REALM=myrealm
      - REACT_APP_AUTH_CLIENT=vanilla
    ports: 
      - '3000:3000'

networks: 
  default:
    external:
      name: dockernet
