apiVersion: v1
kind: Service
metadata:
  name: security-keycloak-react-app-service
spec:
  type: NodePort
  selector:
    component: security-keycloak-react-app
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 30400
